name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # may be actions/checkout@v2 now
    - name: Login to github docker Registry
      run: docker login docker.pkg.github.com -u iamangus -p ${{ secrets.GITHUB_TOKEN }}
    - name: Set Date based var for use in tag
      id: vars
      run: echo ::set-output name=tag::$(echo $(date +%s))
    - name: Build the tagged Docker image
      run: docker build --build-arg VERSION=noavx --build-arg CUSTOM_CPU_FLAGS= --build-arg OLLAMA_SKIP_ROCM_GENERATE=1 --build-arg OLLAMA_FAST_BUILD=1 --platform=linux/amd64 --tag docker.pkg.github.com/iamangus/ollama/ollama-noavx:latest .
    - name: Push the latest Docker image
      run: docker push docker.pkg.github.com/iamangus/ollama/ollama-noavx:latest
    - name: retag and push
      run: docker tag docker.pkg.github.com/iamangus/ollama/ollama-noavx:latest docker.pkg.github.com/iamangus/ollama/ollama-noavx:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push docker.pkg.github.com/iamangus/ollama/ollama-noavx:${{steps.vars.outputs.tag}}